<?php

return [
    'addRole' => 1,
    'rolesFilter' => 2,
    'editRole' => 3,
    'addUser' => 4,
    'usersFilter' => 5,
    'editUser' => 6,
    'requests' => 7,
    'approvedOrganisations' => 8,
    'rejectOrganisations' => 9,
    'editOrganization' => 10,
    'addCommittee' => 13,
    'committeesFilter' => 14,
    'editCommittee' => 15,
    'addMeetingType' => 16,
    'meetingTypesFilter' => 17,
    'editMeetingType' => 18,
    'addTimeZone' => 19,
    'timeZonesFilter' => 20,
    'editTimeZone' => 21,
    'addMeeting' => 22,
    'meetingsFilter' => 23,
    'editMeeting' => 24,
    'deleteRole' => 27,
    'deleteUser' => 28,
    'deleteCommittee' => 29,
    'meetingDashboard' => 30,
    'myCalendar' => 31,
    'editMyOrganization' => 32,
    'addProposal' => 36,
    'proposalsFilter' => 37,
    'showProposal' => 38,
    'deleteMeetingType' => 39,
    'deleteTimeZone' => 40,
    'secertaryDashboard' => 41,
    'participantDashboard' => 42,
    'adminDashboard' => 43,
    'viewMeeting' => 46,
    'meetingAbsenceFilter' => 48,
    'addJobTitle' => 49,
    'jobTitlesFilter' => 50,
    'editJobTitle' => 51,
    'addUserTitle' => 52,
    'userTitlesFilter' => 53,
    'editUserTitle' => 54,
    'addNickname' => 55,
    'nicknamesFilter' => 56,
    'editNickname' => 57,
    'organizationDashboard' => 58,
    'deleteJobTitle' => 59,
    'deleteUserTitle' => 61,
    'deleteNickname' => 62,
    'deleteMeeting' => 63,
    'manageMOM' => 64,
    'addTask' => 65,
    'editTask' => 66,
    'deleteTask' => 67,
    'organizationTasks' => 68,
    'myTasksDashboard' => 69,
    'showTask' => 70,
    'editConfigration' => 71,
    'allCommitteesTasks' => 74,
    'tasksStatistics' => 75,
    'allConversations' => 76,
    'failedLoginAttemptsFilter' => 78,
    'deleteFailedLoginAttempt' => 79,
    'onlineConfigurationsFilter' => 80,
    'addOnlineConfiguration' => 81,
    'editOnlineConfiguration' => 82,
    'deleteOnlineConfiguration' => 83,
    'addMomTemplate' => 84,
    'momTemplatesFilter' => 85,
    'editMomTemplate' => 86,
    'deleteMomTemplate' => 87,
    'addAgendaTemplate' => 88,
    'agendaTemplatesFilter' => 89,
    'editAgendaTemplate' => 90,
    'deleteAgendaTemplate' => 91,
    'addHtmlMomTemplate' => 92,
    'htmlMomTemplatesFilter' => 93,
    'editHtmlMomTemplate' => 94,
    'deleteHtmlMomTemplate' => 95,
    'documentsFilter' => 96,
    'addDocument' => 97,
    'editDocument' => 98,
    'deleteDocument' => 99,
    'viewDocument' => 100,
    'meetingDecisionsFilter' => 101,
    'decisionTypesFilter' => 102,
    'addDecisionType' => 103,
    'editDecisionType' => 104,
    'deleteDecisionType' => 105,
    'circularDecisionsFilter' => 106,
    'addCircularDecision' => 107,
    'editCircularDecision' => 108,
    'deleteCircularDecision' => 109,
    'showCircularDecision' => 110,
    'boardDashboard' => 111,
    'committeesDashboard' => 112,
    'memberDashboard' => 113,
    'files' => 114,
    'faqSectionFilter' => 115,
    'addFaqSection' => 116,
    'editFaqSection' => 117,
    'deleteFaqSection' => 118,
    'faqsFilter' => 119,
    'addFaq' => 120,
    'editFaq' => 121,
    'deleteFaq' => 122,
    'videoGuideFilter' => 123,
    'addVideoGuide' => 124,
    'editVideoGuide' => 125,
    'deleteVideoGuide' => 126,
    'faqTree' => 127,
    'videoGuideHelp' => 128,
    'addShareholder' => 129,
    'shareholdersFilter' => 130,
    'editShareholder' => 131,
    'deleteShareholder' => 134,

    /* Guest Rights */
    'presenting' => 137,
    'canChat' => 138,
    'canShowMom' => 139,
    'canVote' => 140,
    'canShowVoteResults' => 141,
    /* End Guest Rights */

    /* Meeting Page Rights */
    'organizationsSection' => 142,
    'participantsSection' => 143,
    'attachmentsSection' => 144,
    'agendasSection' => 145,
    'votersResultsSection' => 146,
    /* End Meeting Page Rights */

    /* Approval rights */
    'approvalsList' => 147,
    'addApproval' => 148,
    'viewApproval' => 149,
    /* End Approval rights */

    /* Committee Requests Rights */
    'permanentCommittee' => 150,
    'temporaryCommittee' => 151,
    'committeeRequests' => 152,
    'blockUser' => 153,
    'committeeDashboard' => 154,
    /* End Committee Requests Rights */
    'BlockUser' => 153,
    'CommitteesDashboard' => 154,
    'committeeExport' => 155,


    'reminderFinalCommitteeWork' => 156,


    'userEvaluation' => 157,
    'myCommittees' => 158,
];
